/*
 * This source file was generated by the Gradle 'init' task
 */
package com.matthewjohnson42.dataanalytics.oauthservice

import spock.lang.Specification

class DataAnalyticsOAuthServiceTest extends Specification {
    def "main class can be instantiated"() {
        setup:
        def app = new DataAnalyticsOAuthService()

        when:
        true

        then:
        app != null
    }
}
