/*
 * This source file was generated by the Gradle 'init' task
 */
package com.matthewjohnson42.dataanalytics.oauthservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DataAnalyticsOAuthService {

    public static void main(String[] args) {
        SpringApplication.run(DataAnalyticsOAuthService.class);
    }

}
